"""added new tables

Revision ID: 0e70ab992358
Revises: 7a5ad2668e7f
Create Date: 2025-12-21 00:45:49.313069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e70ab992358'
down_revision: Union[str, Sequence[str], None] = '7a5ad2668e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bank_account', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('commission_earned', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('referral_amount', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('guest_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('has_redeemed_guest_code', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('coins_accumulated', sa.Float(), nullable=True))
    op.create_index(op.f('ix_users_guest_code'), 'users', ['guest_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guest_code'), table_name='users')
    op.drop_column('users', 'coins_accumulated')
    op.drop_column('users', 'has_redeemed_guest_code')
    op.drop_column('users', 'guest_code')
    op.drop_column('users', 'referral_amount')
    op.drop_column('users', 'commission_earned')
    op.drop_column('users', 'bank_name')
    op.drop_column('users', 'bank_account')
    op.drop_column('users', 'profile_url')
    # ### end Alembic commands ###
