"""Create export passphrase , notifc, add new

Revision ID: 1fa6c4c7b907
Revises: 89771a612a20
Create Date: 2025-12-13 13:54:24.429439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa6c4c7b907'
down_revision: Union[str, Sequence[str], None] = '89771a612a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('TRANSACTION', 'DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'LOAN_REQUEST', 'LOAN_APPROVED', 'LOAN_REJECTED', 'LOAN_REPAYMENT', 'PAYMENT_LINK', 'PAYMENT_RECEIVED', 'INVESTMENT', 'ACCOUNT', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('users', sa.Column('passphrase_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('celo_address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sui_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sui_address')
    op.drop_column('users', 'celo_address')
    op.drop_column('users', 'passphrase_hash')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
