"""Add uppercase invest enum values

Revision ID: f970f97f7e03
Revises: 43f36db4372d
Create Date: 2025-12-12 12:25:40.136132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f970f97f7e03'
down_revision: Union[str, Sequence[str], None] = '43f36db4372d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE transactiontype ADD VALUE 'INVEST_DEPOSIT'")
        op.execute("ALTER TYPE transactiontype ADD VALUE 'INVEST_CASHOUT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
